#!/usr/bin/env bash

# This script can be run more than once

set -e

if [[ "$(whoami)" != "root" ]]; then
    echo "You need to be root to run this script"
    exit 255
fi

export DEBIAN_FRONTEND=noninteractive
export JH_PKG_MINIMAL_NAME="jehon-base-minimal"

if [ -r repo/"${JH_PKG_MINIMAL_NAME}.deb" ]; then
    LOCAL_DEB="repo/${JH_PKG_MINIMAL_NAME}.deb"
    echo "*** Using local deb: $LOCAL_DEB"
fi

if [ -n "$JH_LOCAL_STORE" ]; then
    LOCAL_DEB="$JH_LOCAL_STORE/${JH_PKG_MINIMAL_NAME}.deb"
    echo "*** Using local store: $LOCAL_DEB"
fi

if [ ! -r "$LOCAL_DEB" ]; then
    echo "*** Installing source from github"
    wget "http://jehon.github.io/packages/jehon-base-minimal.deb" -O "${JH_PKG_MINIMAL_NAME}.deb"
    LOCAL_DEB="./${JH_PKG_MINIMAL_NAME}.deb"
fi

echo "*** Using deb: $LOCAL_DEB"

apt-get install --yes "$LOCAL_DEB"
/usr/bin/jh-apt-configure-repositories.sh

apt-get --yes update
apt-get --yes upgrade

cat <<EOD


*** Install done ***
SSH is enabled through the firewall

You may now install:

1/ download the git repositories:              sudo jh-checkout
2/ setup hyperv:                               sudo jh-setup-hyperv
3/ install packages:                           sudo apt install jehon-base-thirdparties jehon-env-desktop
4/ install snaps:                              sudo apt jh-snap-install

You also need to logout/login to jump into docker group before testing repositories

EOD
