#!/usr/bin/env bash

# This script can be run more than once

set -e

if [[ "$(whoami)" != "root" ]]; then
    echo "You need to be root to run this script"
    exit 255
fi

export DEBIAN_FRONTEND=noninteractive
export DEB_NAME="jehon-base-minimal.deb"

if [ -r repo/"$DEB_NAME" ]; then
    LOCAL_DEB="repo/$DEB_NAME"
    echo "*** Using local deb: $LOCAL_DEB"
fi

if [ -n "$LOCAL_STORE" ]; then
    LOCAL_DEB="$LOCAL_STORE/$DEB_NAME"
    echo "*** Using local store: $LOCAL_DEB"
fi

if [ ! -r "$LOCAL_DEB" ]; then
    echo "*** Installing source from github"
    wget "http://jehon.github.io/packages/jehon-base-minimal.deb" -O "$DEB_NAME"
    LOCAL_DEB="./$DEB_NAME"
fi

echo "*** Using deb: $LOCAL_DEB"

apt-get install --yes "$LOCAL_DEB"
/usr/bin/jh-apt-configure-repositories.sh

apt-get --yes update
apt-get --yes upgrade

echo ""
echo ""
echo ""
echo ""
echo "*** Install done ***"
echo "SSH is enabled through the firewall"
