#!/usr/bin/env bash

# This script can be run more than once

set -e

if [[ "$(whoami)" != "root" ]]; then
    echo "You need to be root to run this script"
    exit 255
fi

export DEBIAN_FRONTEND=noninteractive
export JH_PKG_MINIMAL_NAME="jehon-base-minimal"

if [ -r repo/"${JH_PKG_MINIMAL_NAME}.deb" ]; then
    LOCAL_DEB="repo/${JH_PKG_MINIMAL_NAME}.deb"
    echo "*** Using local deb: $LOCAL_DEB"
fi

if [ -n "$JH_LOCAL_STORE" ]; then
    LOCAL_DEB="$JH_LOCAL_STORE/${JH_PKG_MINIMAL_NAME}.deb"
    echo "*** Using local store: $LOCAL_DEB"
fi

if [ ! -r "$LOCAL_DEB" ]; then
    echo "*** Installing source from github"
    wget "http://jehon.github.io/packages/jehon-base-minimal.deb" -O "${JH_PKG_MINIMAL_NAME}.deb"
    LOCAL_DEB="./${JH_PKG_MINIMAL_NAME}.deb"
fi

echo "*** Using deb: $LOCAL_DEB"

apt-get install --yes "$LOCAL_DEB"
/usr/bin/jh-apt-configure-repositories.sh

apt-get --yes update
apt-get --yes upgrade

echo ""
echo ""
echo ""
echo ""
echo "*** Install done ***"
echo "SSH is enabled through the firewall"
