#!/usr/bin/env bash

if jh-in-docker ; then
    echo "Skipping $0 in docker"
    exit 0
fi

if jh-in-wsl ; then
    echo "Skipping $0 in wsl"
    exit 0
fi

echo "*** Firewall: adapting"
ufw allow ssh
ufw allow OpenSSH
ufw --force enable
# ufw status
echo "*** Firewall: adapted"
