#!/usr/bin/env bash

#
# We activate the repository here, 
# so that they may become available later on if the folder is created
#

if [ -r /home/jehon/Documents/src/packages/repo ]; then
	echo "deb [trusted=yes] file:///home/jehon/Documents/src/packages/repo /" > /etc/apt/sources.list.d/jehon-package-repo.list
else
	rm -f /etc/apt/sources.list.d/jehon-package-repo.list
fi
