#!/usr/bin/env bash

# shellcheck source=/dev/null
. jh-lib.sh

if [ ! -t 1 ] ; then
	exec > >(systemd-cat -t "$(realpath "$0")" -p info ) \
	    2> >(systemd-cat -t "$(realpath "$0")" -p err  )
fi

"/usr/share/$JH_PKG_MINIMAL_NAME/jh-backup-take-snapshot.sh" monthly
