#!/usr/bin/env bash

set -e

REMOTE=$( git remote get-url origin )
MSG=$(head -n 1 "$1")

# Merge branch ...
if [[ $MSG =~ ^Merge\  ]]; then
	exit 0
fi

# Version: 1.2.3
if [[ $MSG =~ ^Version:?\  ]]; then
	exit 0
fi

# Releases
if [[ $MSG =~ ^Releas ]]; then
	exit 0
fi

# https://www.conventionalcommits.org
if [[ $MSG =~ ^[[:alnum:]]+(\(.+\))?: ]]; then
	exit 0
fi

if [[ $REMOTE =~ .+bitbucket.evs.tv.+ ]]; then
	# EVS
	if [[ $MSG =~ ^[A-Z]+-[0-9]+ ]]; then
		exit 0
	fi

	echo "[EVS] You message does not start with a JIRA ticket, chore: or doc:"
	echo "$MSG"
	exit 255
fi

echo "[OTHER] You message does not start with a conventional commit"
exit 255

