#!/usr/bin/env bash

shopt -s nullglob

ROOT=/usr/lib/jehon/
CACHE=/var/cache/jehon

mkdir -p "$CACHE"


################################
#
# Config files
#

CONF="$ROOT/conf"
mkdir -p "$CONF"

if [ ! -z  "$(ls -A $CONF/)" ]; then
	cp --no-dereference -r "$CONF"/* /
fi


################################
#
# Patch
#

PATCHING="$CACHE/patching-files.txt"
PATCHED="$CACHE/patched-files.txt"

# Truncate the file
> "$PATCHING"

# Patch
for S in "$ROOT"/patch/* ; do
	/usr/bin/jh-patch-file.sh "$S" >> "$PATCHING"
done

# Unpatch non patched files
while read L ; do
	I=${L:2}
	FILE=${I%:*}
	TAG=${I#*:}
	if [ -z "$FILE" ]; then
		continue
	fi

	echo "*** $L - $FILE - $TAG"
	/usr/bin/jh-patch-file.sh "uninstall" "$FILE" "$TAG"
done < <( diff --new-file "$PATCHED" "$PATCHING" | grep "<" )

# echo "Commiting the list of patched files"
cp "$PATCHING" "$PATCHED"
rm -f "$PATCHING"

################################
#
# Script
#

for S in "$ROOT"/postUpdate/* ; do
	chmod +x "$S"
	$S
done
