#!/usr/bin/env bash

if [[ "$( id -u )" != "0" ]]; then
    echo "You need to be root to do this" >&2
    exit 1
fi

hasKey() {
    gpg --keyring /etc/apt/trusted.gpg --no-default-keyring --list-key "$1" >/dev/null 2>/dev/null
}

hasKeyOrImport() {
    if ! hasKey "$1" ; then
        echo "Key $2 ($1) does not exists, importing it..."
        apt-key adv --recv-keys --keyserver keyserver.ubuntu.com "$1"
    fi
}

SELF_KEY=/etc/jehon/gpg.packages.pub.asc
SELF_KEY_ID=$(gpg --with-fingerprint "$SELF_KEY" )
if ! hasKey "$SELF_KEY_ID" ; then
    echo "Adding self key $SELF_KEY_ID"
	apt-key add "$SELF_KEY"
fi

hasKeyOrImport "1655A0AB68576280" "nodejs"
hasKeyOrImport "1397BC53640DB551" "Chrome (ubuntu)"
hasKeyOrImport "78BD65473CB3BD13" "Chrome (raspberrypi)"
# hasKeyOrImport "7EA0A9C3F273FCD8" "Docker"

