#!/usr/bin/env bash

if [ ! -t 1 ] ; then
	exec > >(systemd-cat -t "$(realpath "$0")" -p info ) \
	    2> >(systemd-cat -t "$(realpath "$0")" -p err  )
fi

JH_REMOTE_ROOT=/volume3/Backups/$(hostname)
JH_REMOTE_BACKUP=/volume3/transferts/auto/$(hostname)

export JH_REMOTE_ROOT
export JH_REMOTE_BACKUP

# This key is not delivered with packages
KEY="/etc/jehon/restricted/synology_auto"

# TODO: use get config file

if [ -r "$KEY" ]; then
	/usr/bin/jh-rsync-backup.sh \
		/ root@synology:/synology/backup \
		-e "ssh -i $KEY" \
		--filter ". /etc/jehon/jh-rsync-backup-computer-filter" \

else
	echo "No $KEY found, no backup will run"
#	exit 1
fi
