#!/usr/bin/env bash

if [ ! -t 1 ] ; then
	exec > >(systemd-cat -t "$(realpath "$0")" -p info ) \
	    2> >(systemd-cat -t "$(realpath "$0")" -p err  )
fi

ROOT="/var/backups/live"

if [ ! -a /etc/myqsl/debian.cnf ]; then
	echo "Not installed"
	exit 0
fi

MYSQLSEC="--defaults-extra-file=/etc/mysql/debian.cnf"

backupOne() {
	db="$1"
	echo "[$db] Start backup database"

	FILE="$( echo "$db" | sed "s/[^[:alnum:]]/_/g" )"
	FILE="$ROOT/mysql-$FILE.mysql"
	if [ -r "$FILE.gz" ]; then
		rm "$FILE.gz"
	fi

	echo "[$db] Backup the database into $FILE"
	mysqldump $MYSQLSEC --flush-privileges --single-transaction --databases --skip-comments $db > "$FILE"
	if [ -r "$FILE" ]; then
		if [ ! -s "$FILE" ]; then
			echo "[$db] File is empty ! Removing it"
			rm "$FILE"
			return;
		fi
		echo "[$db] Compress backup"
		gzip --no-name "$FILE"
		echo "[$db] Backup done"
	else
		echo "[$db] Backup generate no file"
	fi
}

if [ -z "$2" ]; then
	# for db in "${monthlyBackups[@]}"; do
	echo "show databases" | mysql $MYSQLSEC | while read db ; do
		if [ -z "$db" ]; then return; fi
		if [ "$db" = "information_schema" ]; then return; fi
		if [ "$db" = "performance_schema" ]; then return; fi
		if [ "$db" = "Database" ]; then return; fi

		backupOne "$db"
	done
else
	# Backup only $2
	backupOne "$2"
fi
