#!/usr/bin/env bash

set -e

# shellcheck source=../bin/jh-lib
. jh-lib

HV_ROOT="$( jhGetSharedFile "/usr/share/jehon/hyperv" )"

if [ ! -w /dev/sda1 ]; then
    echo "You should be root to run this script" >&2
    exit 1
fi

header "Grow /dev/sda if possible"
# Take the full place
growpart /dev/sda 1 || true
resize2fs /dev/sda1

inst() {
    if [ -e "$2" ] || [ -L "$2" ]; then
        rm -f "$2"
    fi
    ln -f -s "$1" "$2"
}

# Set the screen size

header "UFW: Waiting for lock"
# Wait for xtable lock to be available
iptables -L -n --wait > /dev/null

header "Configuring grub"
inst "$HV_ROOT"/grub-hyperv.cfg /etc/default/grub.d/80-hyperv.cfg
update-grub
echo ""

header "Configuring the network"
inst "$HV_ROOT"/netplan-hyperv.yaml /etc/netplan/80-hyperv.yaml
netplan apply
echo ""

header "Create the samba share"
header "- Configure service"
jh-patch-file "$HV_ROOT/samba.conf"
service smbd restart
header "- UFW: Enable samba"
ufw allow from 192.168.100.0/24 to any app Samba

header "Reload ufw"
ufw reload

header "Done"
