#!/usr/bin/env bash

shopt -s nullglob

# Where config files are present
ROOT=/usr/lib/jehon/
# Where we store the patching cache
CACHE=/var/cache/jehon

mkdir -p "$CACHE"

################################
#
# Patch
#

# The files that we are patching
PATCHING="$CACHE/patching-files.txt"
# The files that where previously patched (format: "file:tag")
PATCHED="$CACHE/patched-files.txt"

# We did not patch already
truncate --size 0 "$PATCHING"

#
# For all files in $ROOT/patch, do patch it
#    and add it to the PATCHING list
#
for S in "$ROOT"/patch/* ; do
	/usr/bin/jh-patch-file.sh "$S" >> "$PATCHING"
done

#
# Unpatch files
#   For all files that where previously patched (see list in $PATCHED)
#   and that are not patched anymore (not in $PATCHING)
#
while read L ; do
	I=${L:2}
	FILE=${I%:*}
	TAG=${I#*:}
	if [ -z "$FILE" ]; then
		continue
	fi

	# echo "*** $L - $FILE - $TAG"
	/usr/bin/jh-patch-file.sh "uninstall" "$FILE" "$TAG"
done < <( diff --new-file "$PATCHED" "$PATCHING" | grep "<" )

#
# Commiting the list of patched files
#
cp "$PATCHING" "$PATCHED"
rm -f "$PATCHING"

################################
#
# Script
#

for S in "$ROOT"/postUpdate/* ; do
	chmod +x "$S"
	"$S" || echo "** Failed in $S **"
done
