#!/usr/bin/env bash

if [ ! -d /etc/fstab.d ]; then
	echo "Initializing fstab.d"
	mkdir -p /etc/fstab.d
	cp /etc/fstab /etc/fstab.d/10-original.fstab

fi

rm -f /etc/fstab
(
	echo "#"
	echo "# Generated by $0"
	echo "#"
	echo "# DO NOT MODIFY BY HAND - CHANGES WILL BE OVERRIDEN"
	echo "#"
) >> /etc/fstab

for F in $( ls /etc/fstab.d/*.fstab | sort ) ; do
	echo "Adding $(basename "$F" )"
	(	
		echo ""
		echo "#"
		echo "# From $F"
		echo "#"
		cat "$F"
	) >> /etc/fstab
done
