#!/usr/bin/env bash

# shellcheck source=/dev/null
. jh-lib.sh

if [ ! -t 1 ] ; then
	exec > >(systemd-cat -t "$(realpath "$0")" -p info ) \
	    2> >(systemd-cat -t "$(realpath "$0")" -p err  )
fi

# Remove too old backups
# Monthly backups are taken, so 40 days is ok
find "/var/backups/daily" -mtime +40 -delete

"/usr/share/$PKG_NAME/jh-backup-take-snapshot.sh" daily
