#!/usr/bin/env bash

if [ ! -t 1 ] ; then
	exec > >(systemd-cat -t "$(realpath "$0")" -p info ) \
	    2> >(systemd-cat -t "$(realpath "$0")" -p err  )
fi

/usr/share/jehon-base-minimal/jh-backup-take-snapshot.sh monthly
